### ISSUE TITLE
Is it possible to create custom sized tiles?

### ISSUE THREAD

**Issue by Zemledelec** [screwt/openglobusddm#1]
I've found that 128(actually 129) grid size tile looks very beatifull, the example below is mapbox elevation example which works very slow, but looks cool because it uses 128 grid size tiles.
![image](https://user-images.githubusercontent.com/5452251/77195771-378ff580-6af3-11ea-89c2-1cdc24940271.png)

**Comment by screwt** [comment]
I added a command line parameter (-s  or --quadsize)
